using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenTS2.SimAntics
{
    public enum VMGlobals
    {
        Hour,
        DayOfMonth,
        ZoomLevel,
        SelectedPersonID,
        TimeOfDay,
        Minute,
        Second,
        Month,
        Year,
        CurrentFamily,
        CurrentHouse,
        Unused,
        LastGZButtonID,
        BudgetMod10000,
        BudgetDiv10000,
        CurrentLanguage,
        Speed,
        Paused,
        HeldSimSpeed,
        Mode,
        GameEditionFlags1,
        InhibitMoveIn,
        LotHasHouse,
        LotSize,
        CurrentSKU,
        DebugFlags,
        TutorialState,
        IndoorTiles,
        DaysRunning,
        MaximumDayNumber,
        FreeWill,
        HouseRadioStation,
        InterruptOn,
        DemoFlags,
        DayOfWeek,
        ParentalControl,
        CurrentInteractionGUID,
        UtilityAvailableFlags,
        UtilityBillEnergy,
        UtilityBillWater,
        CurrentNeighborhoodID,
        LotZoning,
        AllowAging,
        LastNeighborhoodID,
        LotEntryMethod,
        CinematicCamera,
        LotValueDiv1000,
        LotValueMod1000,
        ObjectsValueDiv1000,
        ObjectsValueMod1000,
        MaxVisitors,
        ObjectErrorFlags,
        CameraBusy,
        InstantWriteOnceFlags,
        NeighborhoodType,
        Unused2,
        PuppyKittenAgingDisabled,
        BugJarTimeDecay,
        GameEditionFlags2,
        LotClass
    }
}
